db.posts.insertMany([
  {
    "Serial Number": "9789384850098",
    "Company Name": "I AM THE MIND",
    "Employee Markme": "DEEP TRIVEDI",
    Description: "AATMARAM & SONS",
    Leave: "0",
  },
  {
    "Serial Number": "9780349121420",
    "Company Name": "THE ART OF CHOOSING",
    "Employee Markme": "SHEEMark IYENGAR",
    Description: "ABACUS",
    Leave: "0",
  },
  {
    "Serial Number": "9780349123462",
    "Company Name": "IN SPITE OF THE GODS",
    "Employee Markme": "EDWARD LUCE",
    Description: "ABACUS",
    Leave: "1",
  },
  {
    "Serial Number": "9788188440061",
    "Company Name": "QUESTIONS & ANWERS ABOUT THE GREAT BIBLE",
    "Employee Markme": "Mark",
    Description: "ABC PUBLISHERS DISTRIBUTORS",
    Leave: "4",
  },
  {
    "Serial Number": "9789382088189",
    "Company Name": "NIBANDH EVAM KAHANI LEKHAN { HINDI }",
    "Employee Markme": "Mark",
    Description: "ABHI BOOKS",
    Leave: "1",
  },
  {
    "Serial Number": "9789332703759",
    "Company Name": "INDIAN ECONOMY SINCE INDEPENDENCE 27TH /E",
    "Employee Markme": "UMA KAPILA",
    Description: "ACADEMIC FOUNDATION",
    Leave: "1",
  },
  {
    "Serial Number": "9788171888016",
    "Company Name": "ECONOMIC DEVELOPMENT AND POLICY IN INDIA",
    "Employee Markme": "UMA KAPILA",
    Description: "ACADEMIC FOUNDATION",
    Leave: "1",
  },
  {
    "Serial Number": "9789332704343",
    "Company Name": "INDIAN ECONOMY PERFORMANCE 18TH/E  2017-2018",
    "Employee Markme": "UMA KAPILA",
    Description: "ACADEMIC FOUNDATION",
    Leave: "2",
  },
  {
    "Serial Number": "9789332703735",
    "Company Name": "INDIAN ECONOMIC DEVELOPMENTSINCE 1947 (NO RETURMarkBLE)",
    "Employee Markme": "UMA KAPILA",
    Description: "ACADEMIC FOUNDATION",
    Leave: "1",
  },
  {
    "Serial Number": "9789383454143",
    "Company Name": "PRELIMS SPECIAL READING COMPREHENSION PAPER II CSAT",
    "Employee Markme": "MarkGENDRA PRATAP",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "0",
  },
  {
    "Serial Number": "9789383454204",
    "Company Name": "THE CONSTITUTION OF INDIA 2ND / E",
    "Employee Markme": "AR KHAN",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "10",
  },
  {
    "Serial Number": "9789386361011",
    "Company Name": "INDIAN HERITAGE ,ART & CULTURE",
    "Employee Markme": "MADHUKAR",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "10",
  },
  {
    "Serial Number": "9789383454303",
    "Company Name": "BHARAT KA SAMVIDHAN",
    "Employee Markme": "AR KHAN",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "4",
  },
  {
    "Serial Number": "9789383454471",
    "Company Name": "ETHICS, INTEGRITY & APTITUDE ( 3RD/E)",
    "Employee Markme": "P N ROY ,G SUBBA RAO",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "10",
  },
  {
    "Serial Number": "9789383454563",
    "Company Name": "GENERAL STUDIES PAPER -- I (2016)",
    "Employee Markme": "Mark",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "0",
  },
  {
    "Serial Number": "9789383454570",
    "Company Name": "GENERAL STUDIES PAPER - II (2016)",
    "Employee Markme": "Mark",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "0",
  },
  {
    "Serial Number": "9789383454693",
    "Company Name": "INDIAN AND WORLD GEOGRAPHY 2E",
    "Employee Markme": "D R KHULLAR",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "10",
  },
  {
    "Serial Number": "9789383454709",
    "Company Name": "VASTUNISTHA PRASHN SANGRAHA: BHARAT KA ITIHAS",
    "Employee Markme": "MEEMarkKSHI KANT",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "0",
  },
  {
    "Serial Number": "9789383454723",
    "Company Name": "PHYSICAL, HUMAN AND ECONOMIC GEOGRAPHY",
    "Employee Markme": "D R KHULLAR",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "4",
  },
  {
    "Serial Number": "9789383454730",
    "Company Name": "WORLD GEOGRAPHY",
    "Employee Markme": "DR KHULLAR",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "5",
  },
  {
    "Serial Number": "9789383454822",
    "Company Name": "INDIA: MAP ENTRIES IN GEOGRAPHY",
    "Employee Markme": "MAJID HUSAIN",
    Description: "ACCESS PUBLISHING INDIA PVT.LTD",
    Leave: "5",
  },
]);
